name: sardunya
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#Managment
  auto_route: ^3.2.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
#Helper
  dartz: ^0.10.1
  flutter_gen: ^4.2.1
  rxdart: ^0.27.3
#Database
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  sqflite: ^2.0.2+1
#Converter
  flutter_hooks: ^0.18.3
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
#Provider
  path_provider: ^2.0.9
#Main Feature
  flutter_local_notifications: ^9.4.1
#Utils
  kt_dart: ^0.10.0
  another_flushbar: ^1.10.28
  flutter_svg: ^1.1.0
  flutter_native_timezone: ^2.0.0
  rename: ^2.0.1
  uuid: ^3.0.6
#Assets
  google_fonts: ^3.0.1
  time_zone_list: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
#Managment
  auto_route_generator: ^3.2.3
  injectable_generator: ^1.5.3
#Converter
  freezed: ^2.0.2
  json_serializable: ^6.1.6
#Helper
  flutter_gen_runner: ^4.2.1
  flutter_lints: ^1.0.4
#Utils
  flutter_launcher_icons: ^0.9.2
#Database
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - google_fonts/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"
  adaptive_icon_background: "#ff6868"
